Repository hmcts/finrem-case-orchestration-service, pull requests merged in 2021-11, with the labels that each got.

#613 DFR-620 - Add suppressions to audit.json
  audit.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-613

#614 DFR-621 - Suppress springframework dependency issue
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-614

#603 DFR-41 Update court contact details
  src/functionalTests/resources/json/contested/hwfPayment.json
  src/functionalTests/resources/json/contested/pba-payment_contested.json
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/PaymentConfirmationController.java
  src/main/resources/markdown/contested-hwf-payment-confirmation.md
  src/main/resources/markdown/contested-pba-payment-confirmation.md
  src/test/resources/fixtures/contested/hwf.json
  src/test/resources/fixtures/contested/pba-validate.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-603

#616 gradle upgrade 7.3
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-616

#618 enable pact test on PR
  Jenkinsfile_CNP
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-618

#619 revert sourceSet change
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-619
