Repository hmcts/finrem-case-orchestration-service, pull requests merged in 2022-03, with the labels that each got.

#640 Java chart Update Chart.yaml
  charts/finrem-cos/Chart.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-640

#641 fix nightly security scan issue
  audit.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-641

#642 DFR-927: fix nightly security scan issue
  security.sh
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-642

#643 Adding jackson versions and bumping chart.yaml java version
  build.gradle
  charts/finrem-cos/Chart.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-643

#645 suppress jackson vul until fixed version available
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-645
