Repository hmcts/finrem-case-orchestration-service, pull requests merged in 2023-11, with the labels that each got.

#1281 DFR-2380-Apply categorisation for approved consent orders
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ConsentOrderApprovedController.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderApprovedDocumentService.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/documentcatergory/ApprovedConsentOrderDocumentCategorizer.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/ConsentOrderApprovedControllerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderApprovedDocumentServiceTest.java
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1281

#1284 Dfr 2442 add default policy if not represented
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseDataController.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DraftOnlineDocumentController.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/CaseDataControllerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/DraftOnlineDocumentControllerTest.java
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1284

#1293 DFR-2388: FR Contested: remove duplicated general applications
  src/main/resources/generalApplicationRemoveCaseReferenceList.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1293

#1296 DFR-2414: remove obsolete contract test
  src/contractTests/java/uk/gov/hmcts/reform/finrem/caseorchestration/contracts/idam/IdamConsumerContractTest.java
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1296

#1290 DFR-2454: added capability in amendcase event if old cases missing ty…
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/AmendCaseContestedAboutToSubmitHandler.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/AmendCaseContestedAboutToSubmitHandlerTest.java
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1290

#1307 fix code smell
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdService.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/GeneralApplicationHelperTest.java
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1307

#1310 DFR-2473: check for empty uploaded document.
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/BulkPrintDocumentService.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/documentgenerator/BulkPrintDocumentServiceTest.java
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1310

#1311 Create stale.yml
  .github/workflows/stale.yml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1311

#1326 DFR-2484: Exception in ClassLoader - NoSuchMethodError
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1326

#1327 DFR-2476: Run Cron to add missing 'Application Type' field on cases w…
  src/main/resources/applicationTypeAddCaseReferenceList.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1327

#1334 DFR-2476: Run Cron to add missing 'Application Type' field on cases w…
  src/main/resources/applicationTypeAddCaseReferenceList.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1334

#1335 DFR-2476: Run Cron to add missing 'Application Type' field on cases w…
  src/main/resources/applicationTypeAddCaseReferenceList.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1335

#1298 Dfr 2385
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/document/DocumentCategory.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralApplicationService.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/documentcatergory/DocumentCategoriser.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/documentcatergory/GeneralApplicationsCategoriser.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationReferToJudgeAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/UpdateGeneralApplicationStatusAboutToStartHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralApplicationServiceTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/documentcategory/GeneralApplicationsCategoriserTest.java
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1298

#1240 Dfr 2349 Avoid sending duplicate notifications list for hearing
  src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/caseorchestration/ValidateHearingDatesTest.java
  src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/documents/FinancialRemedyDocumentGeneratorTests.java
  src/functionalTests/resources/application.properties
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/HearingDocumentController.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ListForHearingContestedAboutToSubmitHandler.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/CCDConfigConstant.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CaseDataService.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingDocumentService.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ValidateHearingService.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/HearingDocumentControllerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ListForHearingContestedAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/ListForHearingContestedSubmittedHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/HearingFastTrackDocumentTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/integrationtest/HearingNonFastTrackDocumentTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/letterdetails/AdditionalHearingDetailsMapperTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AdditionalHearingDocumentServiceTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ValidateHearingServiceTest.java
  src/test/resources/fixtures/bulkprint/bulk-print-additional-hearing.json
  src/test/resources/fixtures/contested/validate-hearing-withoutfastTrackDecision.json
  src/test/resources/fixtures/pba-validate.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1240, use-defs-pr-1353

#1337 DFR-2476: Run Cron to add missing 'Application Type' field on cases w…
  src/main/resources/applicationTypeAddCaseReferenceList.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1337

#1343 DFR-2501: set default org role if party is unrepresented
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SolicitorCreateContestedAboutToSubmitHandler.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/noc/nocworkflows/UpdateRepresentationWorkflowService.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SolicitorCreateContestedAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/UpdateRepresentationWorkflowServiceTest.java
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1343

#1354 DFR-2529: microsoft suggested patch - to deal with no more retries left
  acb.tpl.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1354

#1346 Dfr 2485 court list fix
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/FinremCaseDetailsMapper.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/BaseTask.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/CourtListUpdateTask.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdService.java
  src/main/resources/application.properties
  src/main/resources/courtListUpdateCaseReferenceList.csv
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdServiceTest.java
  src/test/resources/application.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1346

#1360 Fix cve
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1360

#1362 Remove manifest before trying to create it
  acb.tpl.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1362

#1336 DFR-2488 vanilla PR to test issue in preview
  src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/payments/PaymentServiceTests.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GiveAllocationDirectionAboutToSubmitHandler.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/UpdateCourtInfoAboutToSubmitHandler.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/UpdateFrcInformationAboutToSubmitHandler.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/CourtDetailsMapper.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/FinremCaseDetailsMapper.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/EventType.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/AllocatedRegionWrapper.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/DefaultCourtListWrapper.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/BaseTask.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/CourtListUpdateTask.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdService.java
  src/main/resources/application.properties
  src/main/resources/courtListUpdateCaseReferenceList.csv
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GiveAllocationDirectionAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/UpdateCourtInfoAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/UpdateFrcInformationAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/CourtDetailsMapperTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdServiceTest.java
  src/test/resources/application.properties
Labels: ns:financial-remedy, prd:finrem, no-changes, enable_keep_helm, use-defs-pr-1445, rel:finrem-cos-pr-1336

#1368 DFR-2476: Run Cron to add missing 'Application Type' field on cases w…
  src/main/resources/applicationTypeAddCaseReferenceList.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1368

#1374 DFR-2476: Run Cron to add missing 'Application Type' field on cases w…
  src/main/resources/applicationTypeAddCaseReferenceList.csv
  src/main/resources/courtListUpdateCaseReferenceList.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1374

#1375 DFR-2523: Add csv file for to regenerate form a (draft) prod
  src/main/resources/regenerateDraftFormA-PROD.csv
  src/main/resources/regenerateDraftFormA.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1375

#1376 patch - no more retries left
  acb.tpl.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1376

#1379 DFR-2476: Run Cron to add missing 'Application Type' field on cases w…
  src/main/resources/applicationTypeAddCaseReferenceList.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1379

#1283 Dfr 2397 Process order
  acb.tpl.yaml
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/HearingDocumentController.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/DirectionUploadOrderAboutToSubmitHandler.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedAboutToSubmitHandler.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/uploadapprovedorder/UploadApprovedOrderContestedAboutToStartHandler.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/uploadapprovedorder/UploadApprovedOrderContestedAboutToSubmitHandler.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/helper/DocumentHelper.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/DirectionOrder.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/HearingOrderDocument.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AdditionalHearingDocumentService.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ApprovedOrderNoticeOfHearingService.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ContestedOrderApprovedLetterService.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingOrderService.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OrderDateService.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/UploadApprovedOrderService.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/ccd/datamigration/controller/helper/DocumentHelperTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/HearingDocumentControllerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/HearingOrderControllerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/DirectionUploadOrderAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/SendOrderContestedAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/uploadapprovedorder/UploadApprovedOrderBaseHandlerTestSetup.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/uploadapprovedorder/UploadApprovedOrderContestedAboutToStartHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/uploadapprovedorder/UploadApprovedOrderContestedAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AdditionalHearingDocumentServiceTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ApprovedOrderNoticeOfHearingServiceTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ContestedOrderApprovedLetterServiceTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/HearingOrderServiceTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/OrderDateServiceTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/UploadApprovedOrderServiceTest.java
Labels: ns:financial-remedy, prd:finrem, use-defs-pr-1396, rel:finrem-cos-pr-1283

#1382 DFR-2547: disable mutation tests
  Jenkinsfile_nightly
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1382

#1383 DFR-2485: INC5562612: FR contested Exception: There must be exactly o…
  src/main/resources/courtListUpdateCaseReferenceList.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1383

#1386 DFR-2492: Identify cases where either applicant or respondent policy …
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/AddOrganisationPolicyTask.java
  src/main/resources/application.properties
  src/main/resources/organisationPolicyAddCaseReferenceList.csv
  src/test/resources/application.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1386

#1289 DFR-2428 clearing general application directions from previous event …
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/GeneralApplicationDirectionsController.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationDirectionsAboutToStartHandler.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/GeneralApplicationRegionWrapper.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralApplicationDirectionsService.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/controllers/GeneralApplicationDirectionsControllerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationDirectionsAboutToStartHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/GeneralApplicationDirectionsAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/GeneralApplicationDirectionsServiceTest.java
  src/test/resources/fixtures/contested/general-application-direction-start-reset.json
Labels: ns:financial-remedy, prd:finrem, no-changes, enable_keep_helm, rel:finrem-cos-pr-1289, stale

#1388 DFR-2492: Identify cases where either applicant or respondent policy …
  src/main/resources/organisationPolicyAddCaseReferenceList.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1388

#1393 Dfr 2492 apply default org policy remaing cases
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/AddOrganisationPolicyTask.java
  src/main/resources/organisationPolicyAddCaseReferenceList.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1393

#1389 DFR-2548 fixing date issue on additional hearing
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/AdditionalHearingDocumentService.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ApprovedOrderNoticeOfHearingService.java
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1389

#1402 DFR-2543: Enable mutation tests
  Jenkinsfile_nightly
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1402

#1403 DFR-2492: Identify cases where either applicant or respondent policy …
  src/main/resources/organisationPolicyAddCaseReferenceList.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1403

#1405 DFR-2549 setting time for renovate
  .github/renovate.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1405

#1406 DFR-2492: Identify cases where either applicant or respondent policy …
  src/main/resources/organisationPolicyAddCaseReferenceList.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1406

#1408 DFR-2487: highcourt enum
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/Court.java
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1408

#1407 DFR-2485: INC5562612: FR contested Exception: There must be exactly o…
  build.gradle
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/CourtListUpdateTask.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/SpecializedBaseTask.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdService.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/utils/csv/CaseReferenceKeyValue.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/utils/csv/CaseReferenceKeyValueCsvLoader.java
  src/main/resources/courtListUpdateCaseReferenceList.csv
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/CcdServiceTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/utils/csv/CaseReferenceKeyValueCsvLoaderTest.java
  src/test/resources/caserefskeyvalue-test.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1407

#1411 DFR-2485: INC5562612: FR contested Exception: There must be exactly o…
  src/main/resources/courtListUpdateCaseReferenceList.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1411

#1365 DFR-2432: upload approve order
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/uploadapprovedorder/UploadApprovedOrderConsentedAboutToStartHandler.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderApprovedDocumentService.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/uploadapprovedorder/UploadApprovedOrderConsentedAboutToStartHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/ConsentOrderApprovedDocumentServiceTest.java
Labels: ns:financial-remedy, prd:finrem, no-changes, rel:finrem-cos-pr-1365

#1415 DFR-2485: INC5562612: FR contested Exception: There must be exactly o…
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/scheduler/CourtListUpdateTask.java
  src/main/resources/courtListUpdateCaseReferenceList.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1415

#1418 Remove list of cases from csvs
  src/main/resources/applicationTypeAddCaseReferenceList.csv
  src/main/resources/courtListUpdateCaseReferenceList.csv
  src/main/resources/organisationPolicyAddCaseReferenceList.csv
  src/main/resources/regenerateDraftFormA.csv
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1418

#1416 DFR-2563: Error handling improvement
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/intervener/IntervenersAboutToSubmitHandler.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/IntervenerService.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/intervener/IntervenersAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/service/IntervenerServiceTest.java
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1416

#1417 DFR-2558 Reduce amount of logging in application insights for /health
  lib/applicationinsights.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-cos-pr-1417

#1420 DFR-2565 fix for consented court mapping
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/UpdateCourtInfoAboutToSubmitHandler.java
  src/main/java/uk/gov/hmcts/reform/finrem/caseorchestration/model/ccd/wrapper/DefaultCourtListWrapper.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/handler/UpdateCourtInfoAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/caseorchestration/mapper/CourtDetailsMapperTest.java
Labels: ns:financial-remedy, prd:finrem, enable_keep_helm, rel:finrem-cos-pr-1420
